version: 0.2

phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  # post_build:
  #   commands:
  #     - aws s3 cp --recursive ./dist s3://20240319-react-app/
artifacts:
  base-directory: dist
  files:
    - '**/*'
  secondary-artifacts:
    artifact2:
      base-directory: public
      files:
        - '**/*'
